// AUTO-GENERATED by scripts/build-fragments.mjs — do not edit by hand.
// Run `npm run fragments` after changing files under assets/fragments/.
import type { ImageSourcePropType } from 'react-native';

export interface FragmentItem {
  id: string;
  catId: string;
  label: string;
  file: string;
  size: number;
  opacity: number;
  weight: number;
  /** material index for the lighting shader: 0 glass · 1 paper · 2 metal · 3 plastic */
  matType: number;
  /** atlas sub-rect in px: [x, y, w, h] */
  uv: [number, number, number, number];
}
export interface FragmentCategory {
  id: string;
  label: string;
  en: string;
  items: FragmentItem[];
}

export const ATLAS_SIZE = { width: 1000, height: 800 };

/** The packed atlas image (all fragments) — used by the kaleidoscope shader. */
export const FRAGMENT_ATLAS = require('../../assets/fragments/atlas.png');

/** Baked material atlas (RG=normal, B=thickness) — same layout as the atlas. */
export const FRAGMENT_ATLAS_MAT = require('../../assets/fragments/atlas-mat.png');

export const FRAGMENT_CATALOG: FragmentCategory[] = [
  {
    "id": "glass",
    "label": "玻璃",
    "en": "Glass",
    "items": [
      {
        "id": "glass-amber",
        "catId": "glass",
        "label": "Amber",
        "file": "glass/amber.png",
        "size": 1,
        "opacity": 0.82,
        "weight": 1,
        "matType": 0,
        "uv": [
          0,
          0,
          200,
          200
        ]
      },
      {
        "id": "glass-clear",
        "catId": "glass",
        "label": "Clear",
        "file": "glass/clear.png",
        "size": 1,
        "opacity": 0.82,
        "weight": 1,
        "matType": 0,
        "uv": [
          200,
          0,
          200,
          200
        ]
      },
      {
        "id": "glass-cobalt",
        "catId": "glass",
        "label": "Cobalt",
        "file": "glass/cobalt.png",
        "size": 1,
        "opacity": 0.82,
        "weight": 1,
        "matType": 0,
        "uv": [
          400,
          0,
          200,
          200
        ]
      },
      {
        "id": "glass-emerald",
        "catId": "glass",
        "label": "Emerald",
        "file": "glass/emerald.png",
        "size": 1,
        "opacity": 0.82,
        "weight": 1,
        "matType": 0,
        "uv": [
          600,
          0,
          200,
          200
        ]
      },
      {
        "id": "glass-rose",
        "catId": "glass",
        "label": "Rose",
        "file": "glass/rose.png",
        "size": 1,
        "opacity": 0.82,
        "weight": 1,
        "matType": 0,
        "uv": [
          800,
          0,
          200,
          200
        ]
      }
    ]
  },
  {
    "id": "paper",
    "label": "纸片",
    "en": "Paper",
    "items": [
      {
        "id": "paper-blue",
        "catId": "paper",
        "label": "Blue",
        "file": "paper/blue.png",
        "size": 1,
        "opacity": 1,
        "weight": 0.4,
        "matType": 1,
        "uv": [
          0,
          200,
          200,
          200
        ]
      },
      {
        "id": "paper-kraft",
        "catId": "paper",
        "label": "Kraft",
        "file": "paper/kraft.png",
        "size": 1,
        "opacity": 1,
        "weight": 0.4,
        "matType": 1,
        "uv": [
          200,
          200,
          200,
          200
        ]
      },
      {
        "id": "paper-red",
        "catId": "paper",
        "label": "Red",
        "file": "paper/red.png",
        "size": 1,
        "opacity": 1,
        "weight": 0.4,
        "matType": 1,
        "uv": [
          400,
          200,
          200,
          200
        ]
      },
      {
        "id": "paper-white",
        "catId": "paper",
        "label": "White",
        "file": "paper/white.png",
        "size": 1,
        "opacity": 1,
        "weight": 0.4,
        "matType": 1,
        "uv": [
          600,
          200,
          200,
          200
        ]
      },
      {
        "id": "paper-yellow",
        "catId": "paper",
        "label": "Yellow",
        "file": "paper/yellow.png",
        "size": 1,
        "opacity": 1,
        "weight": 0.4,
        "matType": 1,
        "uv": [
          800,
          200,
          200,
          200
        ]
      }
    ]
  },
  {
    "id": "metal",
    "label": "金属",
    "en": "Metal",
    "items": [
      {
        "id": "metal-copper",
        "catId": "metal",
        "label": "Copper",
        "file": "metal/copper.png",
        "size": 1,
        "opacity": 1,
        "weight": 1.35,
        "matType": 2,
        "uv": [
          0,
          400,
          200,
          200
        ]
      },
      {
        "id": "metal-gold",
        "catId": "metal",
        "label": "Gold",
        "file": "metal/gold.png",
        "size": 1,
        "opacity": 1,
        "weight": 1.35,
        "matType": 2,
        "uv": [
          200,
          400,
          200,
          200
        ]
      },
      {
        "id": "metal-silver",
        "catId": "metal",
        "label": "Silver",
        "file": "metal/silver.png",
        "size": 1,
        "opacity": 1,
        "weight": 1.35,
        "matType": 2,
        "uv": [
          400,
          400,
          200,
          200
        ]
      },
      {
        "id": "metal-steel",
        "catId": "metal",
        "label": "Steel",
        "file": "metal/steel.png",
        "size": 1,
        "opacity": 1,
        "weight": 1.35,
        "matType": 2,
        "uv": [
          600,
          400,
          200,
          200
        ]
      }
    ]
  },
  {
    "id": "plastic",
    "label": "塑料",
    "en": "Plastic",
    "items": [
      {
        "id": "plastic-cyan",
        "catId": "plastic",
        "label": "Cyan",
        "file": "plastic/cyan.png",
        "size": 1,
        "opacity": 1,
        "weight": 0.7,
        "matType": 3,
        "uv": [
          800,
          400,
          200,
          200
        ]
      },
      {
        "id": "plastic-lime",
        "catId": "plastic",
        "label": "Lime",
        "file": "plastic/lime.png",
        "size": 1,
        "opacity": 1,
        "weight": 0.7,
        "matType": 3,
        "uv": [
          0,
          600,
          200,
          200
        ]
      },
      {
        "id": "plastic-pink",
        "catId": "plastic",
        "label": "Pink",
        "file": "plastic/pink.png",
        "size": 1,
        "opacity": 1,
        "weight": 0.7,
        "matType": 3,
        "uv": [
          200,
          600,
          200,
          200
        ]
      },
      {
        "id": "plastic-purple",
        "catId": "plastic",
        "label": "Purple",
        "file": "plastic/purple.png",
        "size": 1,
        "opacity": 1,
        "weight": 0.7,
        "matType": 3,
        "uv": [
          400,
          600,
          200,
          200
        ]
      }
    ]
  }
];

/** Per-fragment images — used for thumbnails in the picker UI. */
export const FRAGMENT_THUMBS: Record<string, ImageSourcePropType> = {
  "glass/amber.png": require('../../assets/fragments/glass/amber.png'),
  "glass/clear.png": require('../../assets/fragments/glass/clear.png'),
  "glass/cobalt.png": require('../../assets/fragments/glass/cobalt.png'),
  "glass/emerald.png": require('../../assets/fragments/glass/emerald.png'),
  "glass/rose.png": require('../../assets/fragments/glass/rose.png'),
  "paper/blue.png": require('../../assets/fragments/paper/blue.png'),
  "paper/kraft.png": require('../../assets/fragments/paper/kraft.png'),
  "paper/red.png": require('../../assets/fragments/paper/red.png'),
  "paper/white.png": require('../../assets/fragments/paper/white.png'),
  "paper/yellow.png": require('../../assets/fragments/paper/yellow.png'),
  "metal/copper.png": require('../../assets/fragments/metal/copper.png'),
  "metal/gold.png": require('../../assets/fragments/metal/gold.png'),
  "metal/silver.png": require('../../assets/fragments/metal/silver.png'),
  "metal/steel.png": require('../../assets/fragments/metal/steel.png'),
  "plastic/cyan.png": require('../../assets/fragments/plastic/cyan.png'),
  "plastic/lime.png": require('../../assets/fragments/plastic/lime.png'),
  "plastic/pink.png": require('../../assets/fragments/plastic/pink.png'),
  "plastic/purple.png": require('../../assets/fragments/plastic/purple.png'),
};

export function itemById(id: string): FragmentItem | undefined {
  for (const c of FRAGMENT_CATALOG) {
    const it = c.items.find((i) => i.id === id);
    if (it) return it;
  }
  return undefined;
}
